version: "3"
services:
  app:
    restart: always
    build: .
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn Blockchain.wsgi:application -c gunicorn.conf"
    volumes:
      - .:/Blockchain
      - static-volume:/Blockchain/collected_static
      - static-volume:/Blockchain/source
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - "./mysql:/var/lib/mysql"
    ports:
    - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blockchain
      - MYSQL_USER=block
      - MYSQL_PASSWORD=password
    networks:
      - db_network

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - static-volume:/Blockchain/collected_static
      - ./config/nginx:/etc/nginx/conf.d
      - static-volume:/Blockchain/source
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
